-- MySQL
SELECT CITY, MIN(CHAR_LENGTH(CITY))
FROM STATION
GROUP BY CHAR_LENGTH(CITY), CITY ASC
LIMIT 1;
SELECT CITY, MAX(CHAR_LENGTH(CITY))
FROM STATION
GROUP BY CHAR_LENGTH(CITY) DESC, CITY ASC
LIMIT 1;
